/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexagonal_scrabble;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author osimon8
 */
public class LetterChooser extends javax.swing.JPanel {

    /**
     * Creates new form LetterChooser
     */
    List<Tile> tiles;
    Tile chosen;
    JFrame f;
    BlankTile selected;
    JPanel p;
    public LetterChooser(JPanel orig, JFrame frame, BlankTile selected) {
        initComponents();
        //chosen = null;
        tiles = genTiles();
        f= frame;
        this.selected=selected;
        p=orig;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(245, 245, 245));
        setToolTipText("");
        setLocation(new java.awt.Point(200, 200));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Point pos =this.getMousePosition();
        for(Tile t : tiles){
            if(t!=null && t.contains(pos.getX(),pos.getY())){
                chosen = t;
                if(selected!=null)
                    selected.setVal(t);
                f.dispose();
                p.repaint();
            }
        }
    }//GEN-LAST:event_formMouseClicked
    private List<Tile> genTiles(){
        tiles = new ArrayList<Tile>();
        char[] chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".toCharArray();
        int x=10,y=10,ctr = 0;
        for(char c : chars){
        ctr++;
        Tile t = new Tile(x,y,c,TileBag.getPoints(c));
        tiles.add(t);
        int level = ctr/6;
        x+=60;
        if(x>=360)
            x=10;
        y = 10+(60*level);     
        }
        return tiles;
    }
    public void setTile(BlankTile t){
        selected = t;
    }
public void paintComponent(Graphics g){
    super.paintComponent(g);
    for(Tile t : tiles){
        t.draw(g, new Color(192,3,3));  
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
