/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hexagonal_scrabble;

import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author osimon8
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    private Board b;
    private JFrame frame;
    //Hand h = new Hand();
    Tile t = new BlankTile (100,100);
    private double mouseX;
    private double mouseY;
    private int gameState;
    private LetterChooser c;
    private BlankTile selected;
    private Player currPlayer;
    private List<Player> players;
    public MainMenu() {
        selected = null;
        mouseX=0;
        mouseY=0;
        gameState = 0;
        initComponents();
        jComboBox1.setVisible(false);
        jPopupMenu1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        b = new Board(500,100);
        frame = new JFrame("Choose a Letter");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        c = new LetterChooser(this, frame, selected);
        frame.getContentPane().add(c);
        frame.pack();
        frame.setVisible(false);    
        players = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPopupMenu1.setMaximumSize(new java.awt.Dimension(100, 100));
        jPopupMenu1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPopupMenu1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPopupMenu1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenu1PopupMenuWillBecomeVisible(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        setBackground(new java.awt.Color(125, 217, 255));
        setToolTipText("");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Hexagonal Scrabble");

        jLabel2.setText("Created by Owen Simon");

        jButton1.setText("Play");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2 Players", "3 Players", "4 Players" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Shuffle");

        jButton3.setText("End Turn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(371, 371, 371))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(279, 279, 279)
                .addComponent(jButton3)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(gameState==0){
            System.out.println(TileBag.getInstance().toString());
            System.out.println(Dictionary.getInstance().contains("pizza"));
            jLabel2.setVisible(false);
            jComboBox1.setVisible(true);
            jLabel1.setText("Setup Game");
            jButton1.setText("Next");
            gameState++;
        }
        else if(gameState==1){
            for(int i = 1; i<=jComboBox1.getItemCount(); i++)
                players.add(new Player(i));
            currPlayer = players.get(0);
            jButton1.setVisible(false);
            jLabel2.setVisible(false);
            jComboBox1.setVisible(false);
            jLabel1.setVisible(false);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
        }
    }//GEN-LAST:event_jButton1MouseClicked
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        b.draw(g);
        if(currPlayer!=null)
            currPlayer.getHand().draw(g);
        t.draw(g);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        Point pos =this.getMousePosition();
        mouseX = pos.getX();
        mouseY = pos.getY();
        if(evt.getButton() == MouseEvent.BUTTON1){
            //System.out.println(Dictionary.getInstance().contains("pizza"));
//            if(t.contains(mouseX,mouseY)){
//                if(t.getPoints()==0 && t.getTile()==null){//is a blank tile
//                    selected = (BlankTile)t;
//                    c.setTile(selected);
//                    frame.setVisible(true);
//                }
//            }
            if(currPlayer.getHand()!=null && currPlayer.getHand().contains(mouseX,mouseY)!=null){
                System.out.println(currPlayer.getHand().contains(mouseX,mouseY));
                if(currPlayer.getHand().contains(mouseX,mouseY).getPoints()==0 && currPlayer.getHand().contains(mouseX,mouseY).getTile()==null){//is a blank tile
                    frame.setVisible(true);
                    selected = (BlankTile)currPlayer.getHand().contains(mouseX,mouseY);
                    c.setTile(selected);

                }
            }
        }
        else if(evt.getButton() == MouseEvent.BUTTON3){
            if(currPlayer!=null && currPlayer.getHand().contains(mouseX,mouseY).contains(mouseX,mouseY)){
                if(currPlayer.getHand().contains(mouseX,mouseY).getPoints()==0 && currPlayer.getHand().contains(mouseX,mouseY).getTile()!=null){//is a blank tile
                    currPlayer.getHand().contains(mouseX,mouseY).setTile(null);
                    repaint();
                }
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void jPopupMenu1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenu1PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jPopupMenu1PopupMenuWillBecomeVisible

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        currPlayer = (currPlayer.getNumber()==players.size())?players.get(0):players.get(currPlayer.getNumber()+1);
        repaint();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
